// ==========================================================================
// AUTO-GENERATED — DO NOT EDIT
// Source: packages/database/prisma/schema.prisma
// Generated: 2026-03-11T15:40:45.882Z
// Run: pnpm --filter shared-types generate
// ==========================================================================

export enum UserRole {
  USER = 'USER',
  HOST = 'HOST',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  CUSTOMER = 'CUSTOMER',
  OPERATIONS_ADMIN = 'OPERATIONS_ADMIN',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  SUPPORT_ADMIN = 'SUPPORT_ADMIN',
}

export const UserRoleValues = ['USER', 'HOST', 'ADMIN', 'SUPER_ADMIN', 'CUSTOMER', 'OPERATIONS_ADMIN', 'FINANCE_ADMIN', 'SUPPORT_ADMIN'] as const;

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export const UserStatusValues = ['ACTIVE', 'SUSPENDED', 'DELETED', 'PENDING_VERIFICATION'] as const;

export enum PropertyType {
  APARTMENT = 'APARTMENT',
  HOUSE = 'HOUSE',
  VILLA = 'VILLA',
  STUDIO = 'STUDIO',
  CONDO = 'CONDO',
  TOWNHOUSE = 'TOWNHOUSE',
  COTTAGE = 'COTTAGE',
  CABIN = 'CABIN',
  LOFT = 'LOFT',
  OTHER = 'OTHER',
}

export const PropertyTypeValues = ['APARTMENT', 'HOUSE', 'VILLA', 'STUDIO', 'CONDO', 'TOWNHOUSE', 'COTTAGE', 'CABIN', 'LOFT', 'OTHER'] as const;

export enum PropertyStatus {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  MAINTENANCE = 'MAINTENANCE',
  UNAVAILABLE = 'UNAVAILABLE',
  DRAFT = 'DRAFT',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export const PropertyStatusValues = ['AVAILABLE', 'RENTED', 'MAINTENANCE', 'UNAVAILABLE', 'DRAFT', 'SUSPENDED', 'ARCHIVED'] as const;

export enum AvailabilityStatus {
  AVAILABLE = 'AVAILABLE',
  BOOKED = 'BOOKED',
  BLOCKED = 'BLOCKED',
}

export const AvailabilityStatusValues = ['AVAILABLE', 'BOOKED', 'BLOCKED'] as const;

export enum PropertyCondition {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
}

export const PropertyConditionValues = ['EXCELLENT', 'GOOD', 'FAIR', 'POOR'] as const;

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export const VerificationStatusValues = ['PENDING', 'VERIFIED', 'APPROVED', 'REJECTED'] as const;

export enum BookingStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_OWNER_APPROVAL = 'PENDING_OWNER_APPROVAL',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  CANCELLED = 'CANCELLED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  DISPUTED = 'DISPUTED',
  COMPLETED = 'COMPLETED',
  AWAITING_RETURN_INSPECTION = 'AWAITING_RETURN_INSPECTION',
  REFUNDED = 'REFUNDED',
  SETTLED = 'SETTLED',
}

export const BookingStatusValues = ['DRAFT', 'PENDING', 'PENDING_PAYMENT', 'PENDING_OWNER_APPROVAL', 'CONFIRMED', 'IN_PROGRESS', 'CANCELLED', 'PAYMENT_FAILED', 'DISPUTED', 'COMPLETED', 'AWAITING_RETURN_INSPECTION', 'REFUNDED', 'SETTLED'] as const;

export enum BookingMode {
  REQUEST = 'REQUEST',
  INSTANT_BOOK = 'INSTANT_BOOK',
}

export const BookingModeValues = ['REQUEST', 'INSTANT_BOOK'] as const;

export enum PricingMode {
  PER_NIGHT = 'PER_NIGHT',
  PER_MONTH = 'PER_MONTH',
  PER_HOUR = 'PER_HOUR',
  PER_DAY = 'PER_DAY',
  PER_WEEK = 'PER_WEEK',
  CUSTOM = 'CUSTOM',
}

export const PricingModeValues = ['PER_NIGHT', 'PER_MONTH', 'PER_HOUR', 'PER_DAY', 'PER_WEEK', 'CUSTOM'] as const;

export enum DepositType {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
  NONE = 'NONE',
}

export const DepositTypeValues = ['FIXED', 'PERCENTAGE', 'NONE'] as const;

export enum ListingStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  REJECTED = 'REJECTED',
}

export const ListingStatusValues = ['DRAFT', 'PUBLISHED', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'ARCHIVED', 'PENDING_REVIEW', 'REJECTED'] as const;

export enum ReviewType {
  LISTING_REVIEW = 'LISTING_REVIEW',
  RENTER_REVIEW = 'RENTER_REVIEW',
  OWNER_REVIEW = 'OWNER_REVIEW',
}

export const ReviewTypeValues = ['LISTING_REVIEW', 'RENTER_REVIEW', 'OWNER_REVIEW'] as const;

export enum ReviewStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  HIDDEN = 'HIDDEN',
  FLAGGED = 'FLAGGED',
}

export const ReviewStatusValues = ['DRAFT', 'PUBLISHED', 'HIDDEN', 'FLAGGED'] as const;

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  SUCCEEDED = 'SUCCEEDED',
}

export const PaymentStatusValues = ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', 'SUCCEEDED'] as const;

export enum RefundStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  SUCCEEDED = 'SUCCEEDED',
}

export const RefundStatusValues = ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'SUCCEEDED'] as const;

export enum DepositStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  HELD = 'HELD',
  RELEASED = 'RELEASED',
  CAPTURED = 'CAPTURED',
  FAILED = 'FAILED',
}

export const DepositStatusValues = ['PENDING', 'AUTHORIZED', 'HELD', 'RELEASED', 'CAPTURED', 'FAILED'] as const;

export enum PayoutStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  IN_TRANSIT = 'IN_TRANSIT',
  COMPLETED = 'COMPLETED',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export const PayoutStatusValues = ['PENDING', 'PROCESSING', 'IN_TRANSIT', 'COMPLETED', 'PAID', 'FAILED', 'CANCELLED'] as const;

export enum AccountType {
  REVENUE = 'REVENUE',
  EXPENSE = 'EXPENSE',
  LIABILITY = 'LIABILITY',
  ASSET = 'ASSET',
  EQUITY = 'EQUITY',
  CASH = 'CASH',
  RECEIVABLE = 'RECEIVABLE',
  PAYABLE = 'PAYABLE',
}

export const AccountTypeValues = ['REVENUE', 'EXPENSE', 'LIABILITY', 'ASSET', 'EQUITY', 'CASH', 'RECEIVABLE', 'PAYABLE'] as const;

export enum LedgerSide {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export const LedgerSideValues = ['DEBIT', 'CREDIT'] as const;

export enum TransactionType {
  PLATFORM_FEE = 'PLATFORM_FEE',
  SERVICE_FEE = 'SERVICE_FEE',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  PAYOUT = 'PAYOUT',
  DEPOSIT_HOLD = 'DEPOSIT_HOLD',
  OWNER_EARNING = 'OWNER_EARNING',
  DEPOSIT_RELEASE = 'DEPOSIT_RELEASE',
  DISPUTE = 'DISPUTE',
}

export const TransactionTypeValues = ['PLATFORM_FEE', 'SERVICE_FEE', 'PAYMENT', 'REFUND', 'PAYOUT', 'DEPOSIT_HOLD', 'OWNER_EARNING', 'DEPOSIT_RELEASE', 'DISPUTE'] as const;

export enum LedgerEntryStatus {
  PENDING = 'PENDING',
  POSTED = 'POSTED',
  SETTLED = 'SETTLED',
  CANCELLED = 'CANCELLED',
}

export const LedgerEntryStatusValues = ['PENDING', 'POSTED', 'SETTLED', 'CANCELLED'] as const;

export enum NotificationType {
  BOOKING_REQUEST = 'BOOKING_REQUEST',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_REMINDER = 'BOOKING_REMINDER',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  SYSTEM_UPDATE = 'SYSTEM_UPDATE',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  MARKETING = 'MARKETING',
  PAYOUT_PROCESSED = 'PAYOUT_PROCESSED',
  VERIFICATION_COMPLETE = 'VERIFICATION_COMPLETE',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  DISPUTE_UPDATED = 'DISPUTE_UPDATED',
  NEW_MESSAGE = 'NEW_MESSAGE',
  LISTING_APPROVED = 'LISTING_APPROVED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
}

export const NotificationTypeValues = ['BOOKING_REQUEST', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'BOOKING_REMINDER', 'PAYMENT_RECEIVED', 'REVIEW_RECEIVED', 'MESSAGE_RECEIVED', 'SYSTEM_UPDATE', 'SYSTEM_ANNOUNCEMENT', 'MARKETING', 'PAYOUT_PROCESSED', 'VERIFICATION_COMPLETE', 'DISPUTE_OPENED', 'DISPUTE_UPDATED', 'NEW_MESSAGE', 'LISTING_APPROVED', 'PAYMENT_REFUNDED'] as const;

export enum OrganizationStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export const OrganizationStatusValues = ['ACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION'] as const;

export enum OrganizationRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export const OrganizationRoleValues = ['OWNER', 'ADMIN', 'MEMBER'] as const;

export enum InsuranceType {
  PROPERTY_DAMAGE = 'PROPERTY_DAMAGE',
  LIABILITY = 'LIABILITY',
  TRIP_CANCELLATION = 'TRIP_CANCELLATION',
  MEDICAL = 'MEDICAL',
}

export const InsuranceTypeValues = ['PROPERTY_DAMAGE', 'LIABILITY', 'TRIP_CANCELLATION', 'MEDICAL'] as const;

export enum InsuranceStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  PENDING = 'PENDING',
}

export const InsuranceStatusValues = ['ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING'] as const;

export enum ClaimStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSING = 'PROCESSING',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export const ClaimStatusValues = ['PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'PAID', 'CANCELLED'] as const;

export enum EmailTemplateType {
  BOOKING_CONFIRMATION = 'BOOKING_CONFIRMATION',
  BOOKING_CANCELLATION = 'BOOKING_CANCELLATION',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  WELCOME = 'WELCOME',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  LISTING_APPROVED = 'LISTING_APPROVED',
  LISTING_REJECTED = 'LISTING_REJECTED',
  REVIEW_REMINDER = 'REVIEW_REMINDER',
  PAYOUT_NOTIFICATION = 'PAYOUT_NOTIFICATION',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
}

export const EmailTemplateTypeValues = ['BOOKING_CONFIRMATION', 'BOOKING_CANCELLATION', 'PAYMENT_CONFIRMATION', 'PAYMENT_RECEIPT', 'WELCOME', 'PASSWORD_RESET', 'EMAIL_VERIFICATION', 'LISTING_APPROVED', 'LISTING_REJECTED', 'REVIEW_REMINDER', 'PAYOUT_NOTIFICATION', 'DISPUTE_OPENED', 'DISPUTE_RESOLVED', 'SYSTEM_NOTIFICATION'] as const;

export enum ConversationType {
  GENERAL = 'GENERAL',
  BOOKING = 'BOOKING',
  DISPUTE = 'DISPUTE',
  SUPPORT = 'SUPPORT',
}

export const ConversationTypeValues = ['GENERAL', 'BOOKING', 'DISPUTE', 'SUPPORT'] as const;

export enum ConversationStatus {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  CLOSED = 'CLOSED',
}

export const ConversationStatusValues = ['ACTIVE', 'ARCHIVED', 'CLOSED'] as const;

export enum MessageType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  DOCUMENT = 'DOCUMENT',
  LOCATION = 'LOCATION',
  SYSTEM = 'SYSTEM',
}

export const MessageTypeValues = ['TEXT', 'IMAGE', 'DOCUMENT', 'LOCATION', 'SYSTEM'] as const;

export enum DisputeType {
  PROPERTY_DAMAGE = 'PROPERTY_DAMAGE',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  CANCELLATION = 'CANCELLATION',
  CLEANING_FEE = 'CLEANING_FEE',
  RULES_VIOLATION = 'RULES_VIOLATION',
  MISSING_ITEMS = 'MISSING_ITEMS',
  CONDITION_MISMATCH = 'CONDITION_MISMATCH',
  REFUND_REQUEST = 'REFUND_REQUEST',
  OTHER = 'OTHER',
}

export const DisputeTypeValues = ['PROPERTY_DAMAGE', 'PAYMENT_ISSUE', 'CANCELLATION', 'CLEANING_FEE', 'RULES_VIOLATION', 'MISSING_ITEMS', 'CONDITION_MISMATCH', 'REFUND_REQUEST', 'OTHER'] as const;

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  DISMISSED = 'DISMISSED',
  WITHDRAWN = 'WITHDRAWN',
}

export const DisputeStatusValues = ['OPEN', 'UNDER_REVIEW', 'INVESTIGATING', 'RESOLVED', 'CLOSED', 'DISMISSED', 'WITHDRAWN'] as const;

export enum DisputePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export const DisputePriorityValues = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'] as const;

export enum ResolutionType {
  FULL_REFUND = 'FULL_REFUND',
  PARTIAL_REFUND = 'PARTIAL_REFUND',
  CHARGE_BACK = 'CHARGE_BACK',
  COMPENSATION = 'COMPENSATION',
  DISMISSED = 'DISMISSED',
}

export const ResolutionTypeValues = ['FULL_REFUND', 'PARTIAL_REFUND', 'CHARGE_BACK', 'COMPENSATION', 'DISMISSED'] as const;

export enum IdentityDocumentType {
  DRIVERS_LICENSE = 'DRIVERS_LICENSE',
  PASSPORT = 'PASSPORT',
  NATIONAL_ID = 'NATIONAL_ID',
  OTHER = 'OTHER',
}

export const IdentityDocumentTypeValues = ['DRIVERS_LICENSE', 'PASSPORT', 'NATIONAL_ID', 'OTHER'] as const;

export enum AvailabilityMode {
  DATE_RANGE = 'DATE_RANGE',
  TIME_SLOT = 'TIME_SLOT',
  CALENDAR = 'CALENDAR',
}

export const AvailabilityModeValues = ['DATE_RANGE', 'TIME_SLOT', 'CALENDAR'] as const;

export enum AvailabilitySlotStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  BOOKED = 'BOOKED',
  BLOCKED = 'BLOCKED',
  MAINTENANCE = 'MAINTENANCE',
}

export const AvailabilitySlotStatusValues = ['AVAILABLE', 'RESERVED', 'BOOKED', 'BLOCKED', 'MAINTENANCE'] as const;

export enum PriceLineType {
  BASE_RATE = 'BASE_RATE',
  DURATION_DISCOUNT = 'DURATION_DISCOUNT',
  CLEANING_FEE = 'CLEANING_FEE',
  SERVICE_FEE = 'SERVICE_FEE',
  PLATFORM_FEE = 'PLATFORM_FEE',
  SECURITY_DEPOSIT = 'SECURITY_DEPOSIT',
  INSURANCE = 'INSURANCE',
  TAX = 'TAX',
  DELIVERY_FEE = 'DELIVERY_FEE',
  LATE_FEE = 'LATE_FEE',
  DAMAGE_FEE = 'DAMAGE_FEE',
  CUSTOM = 'CUSTOM',
}

export const PriceLineTypeValues = ['BASE_RATE', 'DURATION_DISCOUNT', 'CLEANING_FEE', 'SERVICE_FEE', 'PLATFORM_FEE', 'SECURITY_DEPOSIT', 'INSURANCE', 'TAX', 'DELIVERY_FEE', 'LATE_FEE', 'DAMAGE_FEE', 'CUSTOM'] as const;

export enum PolicyType {
  TAX = 'TAX',
  FEE = 'FEE',
  PRICING = 'PRICING',
  CANCELLATION = 'CANCELLATION',
  BOOKING_CONSTRAINT = 'BOOKING_CONSTRAINT',
  COMPLIANCE = 'COMPLIANCE',
  CURRENCY = 'CURRENCY',
  IDENTITY = 'IDENTITY',
}

export const PolicyTypeValues = ['TAX', 'FEE', 'PRICING', 'CANCELLATION', 'BOOKING_CONSTRAINT', 'COMPLIANCE', 'CURRENCY', 'IDENTITY'] as const;

export enum PolicyStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export const PolicyStatusValues = ['DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'ARCHIVED'] as const;

export enum PricingRuleType {
  DYNAMIC = 'DYNAMIC',
  SEASONAL = 'SEASONAL',
  OCCUPANCY = 'OCCUPANCY',
  LAST_MINUTE = 'LAST_MINUTE',
  EARLY_BIRD = 'EARLY_BIRD',
  COMPETITOR = 'COMPETITOR',
  SURGE = 'SURGE',
  LOYALTY = 'LOYALTY',
}

export const PricingRuleTypeValues = ['DYNAMIC', 'SEASONAL', 'OCCUPANCY', 'LAST_MINUTE', 'EARLY_BIRD', 'COMPETITOR', 'SURGE', 'LOYALTY'] as const;

export enum PricingStrategy {
  MULTIPLIER = 'MULTIPLIER',
  FIXED_OFFSET = 'FIXED_OFFSET',
  PERCENTAGE = 'PERCENTAGE',
  FLOOR_CEILING = 'FLOOR_CEILING',
  TIERED = 'TIERED',
}

export const PricingStrategyValues = ['MULTIPLIER', 'FIXED_OFFSET', 'PERCENTAGE', 'FLOOR_CEILING', 'TIERED'] as const;

export enum TrustScoreType {
  HOST_RELIABILITY = 'HOST_RELIABILITY',
  RENTER_RELIABILITY = 'RENTER_RELIABILITY',
  PAYMENT_RELIABILITY = 'PAYMENT_RELIABILITY',
  COMMUNICATION = 'COMMUNICATION',
  OVERALL = 'OVERALL',
}

export const TrustScoreTypeValues = ['HOST_RELIABILITY', 'RENTER_RELIABILITY', 'PAYMENT_RELIABILITY', 'COMMUNICATION', 'OVERALL'] as const;

export enum TrustTier {
  NEW = 'NEW',
  BASIC = 'BASIC',
  ESTABLISHED = 'ESTABLISHED',
  TRUSTED = 'TRUSTED',
  SUPERHOST = 'SUPERHOST',
}

export const TrustTierValues = ['NEW', 'BASIC', 'ESTABLISHED', 'TRUSTED', 'SUPERHOST'] as const;

export enum ComplianceCheckType {
  IDENTITY_VERIFICATION = 'IDENTITY_VERIFICATION',
  TAX_REGISTRATION = 'TAX_REGISTRATION',
  BUSINESS_LICENSE = 'BUSINESS_LICENSE',
  INSURANCE_COVERAGE = 'INSURANCE_COVERAGE',
  PROPERTY_PERMIT = 'PROPERTY_PERMIT',
  SAFETY_INSPECTION = 'SAFETY_INSPECTION',
  DATA_PRIVACY = 'DATA_PRIVACY',
  AML_CHECK = 'AML_CHECK',
  SANCTIONS_CHECK = 'SANCTIONS_CHECK',
  AGE_VERIFICATION = 'AGE_VERIFICATION',
}

export const ComplianceCheckTypeValues = ['IDENTITY_VERIFICATION', 'TAX_REGISTRATION', 'BUSINESS_LICENSE', 'INSURANCE_COVERAGE', 'PROPERTY_PERMIT', 'SAFETY_INSPECTION', 'DATA_PRIVACY', 'AML_CHECK', 'SANCTIONS_CHECK', 'AGE_VERIFICATION'] as const;

export enum ComplianceStatus {
  PENDING = 'PENDING',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  WAIVED = 'WAIVED',
  IN_REVIEW = 'IN_REVIEW',
}

export const ComplianceStatusValues = ['PENDING', 'PASSED', 'FAILED', 'EXPIRED', 'WAIVED', 'IN_REVIEW'] as const;

export enum EscrowStatus {
  PENDING = 'PENDING',
  FUNDED = 'FUNDED',
  PARTIALLY_RELEASED = 'PARTIALLY_RELEASED',
  RELEASED = 'RELEASED',
  DISPUTED = 'DISPUTED',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}

export const EscrowStatusValues = ['PENDING', 'FUNDED', 'PARTIALLY_RELEASED', 'RELEASED', 'DISPUTED', 'REFUNDED', 'FAILED'] as const;

export enum EscalationLevel {
  PEER = 'PEER',
  SUPPORT = 'SUPPORT',
  MEDIATOR = 'MEDIATOR',
  SENIOR_MEDIATOR = 'SENIOR_MEDIATOR',
  LEGAL = 'LEGAL',
  EXECUTIVE = 'EXECUTIVE',
}

export const EscalationLevelValues = ['PEER', 'SUPPORT', 'MEDIATOR', 'SENIOR_MEDIATOR', 'LEGAL', 'EXECUTIVE'] as const;

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export const CampaignStatusValues = ['DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED'] as const;

export enum AgentType {
  GENERAL = 'GENERAL',
  BOOKING_ASSISTANT = 'BOOKING_ASSISTANT',
  HOST_ADVISOR = 'HOST_ADVISOR',
  DISPUTE_GUIDE = 'DISPUTE_GUIDE',
  CONCIERGE = 'CONCIERGE',
}

export const AgentTypeValues = ['GENERAL', 'BOOKING_ASSISTANT', 'HOST_ADVISOR', 'DISPUTE_GUIDE', 'CONCIERGE'] as const;

export enum AiConversationStatus {
  ACTIVE = 'ACTIVE',
  RESOLVED = 'RESOLVED',
  ESCALATED = 'ESCALATED',
  ABANDONED = 'ABANDONED',
}

export const AiConversationStatusValues = ['ACTIVE', 'RESOLVED', 'ESCALATED', 'ABANDONED'] as const;

export enum ExpansionStatus {
  EVALUATED = 'EVALUATED',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  LAUNCHED = 'LAUNCHED',
  REJECTED = 'REJECTED',
}

export const ExpansionStatusValues = ['EVALUATED', 'APPROVED', 'IN_PROGRESS', 'LAUNCHED', 'REJECTED'] as const;

export enum SearchType {
  TEXT = 'TEXT',
  MAP = 'MAP',
  IMAGE = 'IMAGE',
  SEMANTIC = 'SEMANTIC',
  VOICE = 'VOICE',
}

export const SearchTypeValues = ['TEXT', 'MAP', 'IMAGE', 'SEMANTIC', 'VOICE'] as const;

export enum ReputationTier {
  NEW = 'NEW',
  BRONZE = 'BRONZE',
  SILVER = 'SILVER',
  GOLD = 'GOLD',
  PLATINUM = 'PLATINUM',
  SUPERHOST = 'SUPERHOST',
}

export const ReputationTierValues = ['NEW', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'SUPERHOST'] as const;

export enum ModerationStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
}

export const ModerationStatusValues = ['PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'ESCALATED'] as const;

export enum HealthStatus {
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  UNHEALTHY = 'UNHEALTHY',
  UNKNOWN = 'UNKNOWN',
}

export const HealthStatusValues = ['HEALTHY', 'DEGRADED', 'UNHEALTHY', 'UNKNOWN'] as const;

export enum AnomalySeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export const AnomalySeverityValues = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as const;

// Utility type: extract union from enum
export type EnumValues<T extends Record<string, string>> = T[keyof T];
