// ============================================================================
// Shared Enums - Single Source of Truth
// Prisma-derived enums: auto-generated from schema.prisma via:
//   pnpm --filter shared-types generate
// Non-Prisma enums: maintained manually below
// ============================================================================

// Re-export all Prisma-generated enums
export {
  BookingStatus,
  BookingMode,
  ListingStatus,
  UserRole,
  UserStatus,
  DisputeStatus,
  DisputeType,
  DisputePriority,
  ReviewType,
  ReviewStatus,
  PaymentStatus,
  RefundStatus,
  PayoutStatus,
  DepositStatus,
  DepositType,
  NotificationType,
  OrganizationRole,
  OrganizationStatus,
  PropertyStatus,
  PropertyType,
  PropertyCondition,
  PricingMode,
  VerificationStatus,
  AccountType,
  LedgerSide,
  TransactionType,
  LedgerEntryStatus,
  InsuranceType,
  InsuranceStatus,
  ClaimStatus,
  EmailTemplateType,
  ConversationType,
  ConversationStatus,
  MessageType,
  ResolutionType,
  IdentityDocumentType,
  AvailabilityMode,
  AvailabilitySlotStatus,
  AvailabilityStatus,
  PriceLineType,
  PolicyType,
  PolicyStatus,
  PricingRuleType,
  PricingStrategy,
  TrustScoreType,
  TrustTier,
  ComplianceCheckType,
  ComplianceStatus,
  EscrowStatus,
  EscalationLevel,
  CampaignStatus,
  AgentType,
  AiConversationStatus,
  ExpansionStatus,
  SearchType,
  ReputationTier,
  ModerationStatus,
  HealthStatus,
  AnomalySeverity,
  BookingStatusValues,
  BookingModeValues,
  ListingStatusValues,
  UserRoleValues,
  UserStatusValues,
  DisputeStatusValues,
  DisputeTypeValues,
  DisputePriorityValues,
  ReviewTypeValues,
  ReviewStatusValues,
  PaymentStatusValues,
  RefundStatusValues,
  PayoutStatusValues,
  DepositStatusValues,
  DepositTypeValues,
  NotificationTypeValues,
  OrganizationRoleValues,
  OrganizationStatusValues,
  PropertyStatusValues,
  PropertyTypeValues,
  PropertyConditionValues,
  PricingModeValues,
  VerificationStatusValues,
  AccountTypeValues,
  LedgerSideValues,
  TransactionTypeValues,
  LedgerEntryStatusValues,
  InsuranceTypeValues,
  InsuranceStatusValues,
  ClaimStatusValues,
  EmailTemplateTypeValues,
  ConversationTypeValues,
  ConversationStatusValues,
  MessageTypeValues,
  ResolutionTypeValues,
  IdentityDocumentTypeValues,
  AvailabilityModeValues,
  AvailabilitySlotStatusValues,
  AvailabilityStatusValues,
  PriceLineTypeValues,
  PolicyTypeValues,
  PolicyStatusValues,
  PricingRuleTypeValues,
  PricingStrategyValues,
  TrustScoreTypeValues,
  TrustTierValues,
  ComplianceCheckTypeValues,
  ComplianceStatusValues,
  EscrowStatusValues,
  EscalationLevelValues,
  CampaignStatusValues,
  AgentTypeValues,
  AiConversationStatusValues,
  ExpansionStatusValues,
  SearchTypeValues,
  ReputationTierValues,
  ModerationStatusValues,
  HealthStatusValues,
  AnomalySeverityValues,
} from './enums.generated';

export type { EnumValues } from './enums.generated';

// ============================================================================
// Non-Prisma enums (frontend/API conventions)
// ============================================================================

export enum DeliveryMethod {
  PICKUP = 'pickup',
  DELIVERY = 'delivery',
  SHIPPING = 'shipping',
}

export enum CancellationPolicy {
  FLEXIBLE = 'flexible',
  MODERATE = 'moderate',
  STRICT = 'strict',
}

export enum ItemCondition {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
}

export enum SearchSortBy {
  PRICE_ASC = 'price-asc',
  PRICE_DESC = 'price-desc',
  RATING = 'rating',
  NEWEST = 'newest',
  POPULAR = 'popular',
}
