import { index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("about", "routes/about.tsx"),
  route("careers", "routes/careers.tsx"),
  route("press", "routes/press.tsx"),
  route("how-it-works", "routes/how-it-works.tsx"),
  route("insurance", "routes/insurance.tsx"),
  route("owner-guide", "routes/owner-guide.tsx"),
  route("earnings", "routes/earnings.tsx"),
  route("help", "routes/help.tsx"),
  route("contact", "routes/contact.tsx"),
  route("safety", "routes/safety.tsx"),
  route("terms", "routes/terms.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("cookies", "routes/cookies.tsx"),
  route("auth/login", "routes/auth.login.tsx"),
  route("auth/signup", "routes/auth.signup.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("auth/forgot-password", "routes/auth.forgot-password.tsx"),
  route("auth/reset-password", "routes/auth.reset-password.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("dashboard/owner", "routes/dashboard.owner.tsx"),
  route("dashboard/owner/calendar", "routes/dashboard.owner.calendar.tsx"),
  route("dashboard/owner/earnings", "routes/dashboard.owner.earnings.tsx"),
  route("dashboard/owner/insights", "routes/dashboard.owner.insights.tsx"),
  route("dashboard/owner/performance", "routes/dashboard.owner.performance.tsx"),
  route("dashboard/renter", "routes/dashboard.renter.tsx"),
  route("bookings", "routes/bookings.tsx"),
  route("bookings/:id", "routes/bookings.$id.tsx"),
  route("checkout/:bookingId", "routes/checkout.$bookingId.tsx"),
  route("listings/new", "routes/listings.new.tsx"),
  route("listings/:id", "routes/listings.$id.tsx"),
  route("listings/:id/edit", "routes/listings.$id.edit.tsx"),
  route("messages", "routes/messages.tsx"),
  route("favorites", "routes/favorites.tsx"),
  route("become-owner", "routes/become-owner.tsx"),
  route("disputes", "routes/disputes.tsx"),
  route("disputes/:id", "routes/disputes.$id.tsx"),
  route("listings", "routes/listings._index.tsx"),
  route("payments", "routes/payments.tsx"),
  route("reviews", "routes/reviews.tsx"),
  route("settings", "routes/settings.tsx"),
  route("insurance/upload", "routes/insurance.upload.tsx"),
  route("disputes/new/:bookingId", "routes/disputes.new.$bookingId.tsx"),
  route("organizations", "routes/organizations._index.tsx"),
  route("organizations/create", "routes/organizations.new.tsx"),
  route(
    "organizations/:id/settings",
    "routes/organizations.$id.settings.tsx"
  ),
  route("organizations/:id/members", "routes/organizations.$id.members.tsx"),
  route("organizations/:id/listings", "routes/organizations.$id.listings.tsx"),
  route("profile/:userId", "routes/profile.$userId.tsx"),
  route("search", "routes/search.tsx"),
  route("settings/profile", "routes/settings.profile.tsx"),
  route("settings/notifications", "routes/settings.notifications.tsx"),
  route("notifications", "routes/notifications.tsx"),

  // Admin routes with generic pattern
  route("admin", "routes/admin/_layout.tsx", [
    index("routes/admin/_index.tsx"),
    route("analytics", "routes/admin/analytics.tsx"),
    route("entities/:entity", "routes/admin/entities/[entity].tsx"),
    route("disputes", "routes/admin/disputes.tsx"),
    route("fraud", "routes/admin/fraud.tsx"),
    route("system", "routes/admin/system/_index.tsx"),
    route("system/general", "routes/admin/system/general.tsx"),
    route("system/database", "routes/admin/system/database.tsx"),
    route("system/notifications", "routes/admin/system/notifications.tsx"),
    route("system/security", "routes/admin/system/security.tsx"),
    route("system/api-keys", "routes/admin/system/api-keys.tsx"),
    route("system/backups", "routes/admin/system/backups.tsx"),
    route("system/email", "routes/admin/system/email.tsx"),
    route("system/environment", "routes/admin/system/environment.tsx"),
    route("system/logs", "routes/admin/system/logs.tsx"),
    route("system/audit", "routes/admin/system/audit.tsx"),
    route(
      "system/power-operations",
      "routes/admin/system/power-operations.tsx"
    ),
  ]),
];
