events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;
    server_name _;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
      try_files $uri =404;
    }

    location / {
      return 200 "certbot bootstrap server\n";
      add_header Content-Type text/plain;
    }
  }
}
